version: "3.2"
services:
  web:
    image: cs162-barter-marketplace
    depends_on:
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 64M
      restart_policy:
        condition: "on-failure"
    ports:
      - 5000:5000
    networks:
      - webnet
    volumes:
      - .:/app

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "cs162"
      POSTGRES_USER: "group1"
      POSTGRES_PASSWORD: "minervaMarketplace"
    networks:
      - webnet
    deploy:
      restart_policy:
        condition: "on-failure"

  adminer:
    image: adminer
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: "on-failure"
    ports:
      - 8080:8080
    networks:
      - webnet
networks:
  webnet:
